import type { MetadataRoute } from 'next';
import { sidebarLinks, currentDocsVersion, websiteUrl } from '@/constants';
import { buildVersionedSidebar } from '@/utils';
import type { Page } from '@/types';
import lastmodMap from '@/generated/sitemap-lastmod.json';

function flattenHrefs(pages: Page[]): string[] {
  return pages.flatMap(page => {
    if (page.pages) {
      return flattenHrefs(page.pages);
    }
    return page.href ? [page.href] : [];
  });
}

/**
 * Generated from `sidebarLinks`, current version only — stays in sync with
 * the sidebar without a separate route list to maintain. Older versions
 * (`/v1/**`) are noindex, so they're deliberately excluded: a noindexed URL
 * in the sitemap is a GSC "Submitted URL marked 'noindex'" error.
 *
 * `lastModified` per route comes from `src/generated/sitemap-lastmod.json`
 * (each page file's last git commit date), regenerated by the `prebuild` /
 * `predev` script `scripts/gen-sitemap-lastmod.mjs`. That keeps the fs/git
 * access out of the app bundle — doing it inline made Turbopack trace the
 * whole project. A build timestamp is avoided on purpose: it would mark every
 * URL modified on every deploy, and Google discounts a sitemap's lastmod once
 * it stops looking trustworthy.
 *
 * `changeFrequency` is omitted — Google ignores it entirely.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const hrefs = flattenHrefs(buildVersionedSidebar(sidebarLinks, currentDocsVersion));
  const lastmod: Record<string, string> = lastmodMap;

  return ['/', ...hrefs].map(href => ({
    url: `${websiteUrl}${href}`,
    lastModified: lastmod[href]
  }));
}
